### ISSUE TITLE
Execute queries with POST

### ISSUE THREAD

**Issue by tadejstanic** [redound/graphiql-app#1]
I've tried this excellent app but unfortunately it doesn't work with this graphql server implementation https://github.com/apollostack/graphql-server

The problem is, that 'graphql-server' accepts only POST method and this app execute queries with GET method.

**Comment by olivierandriessen** [comment]
@tadejstanic I've just released 0.3.2 with POST/GET method switch. Let me know if it works for you.

**Comment by tadejstanic** [comment]
It works! Thx
