### ISSUE TITLE
always initializing

### ISSUE THREAD

**Issue by wowbarry** [redound/graphiql-app#34]
hi guys
I have some problems.
when i open the graphql-ide, it is always initializing.
what should i do.thanks！

**Comment by jimii** [comment]
removing data from ```/Users/[username]/Library/Application Support/graphql-ide``` helps

**Comment by wowbarry** [comment]
thanks！

**Comment by MasterMind92** [comment]
hey guys i've the tried the solution above but i can't find the "Library" directory this is really confusing i'm on windows 10 32 bit please guys
